### ISSUE TITLE
ゲームが立ち上がりません

### ISSUE THREAD

**Issue by vdn39c** [ManlyMarco/HC-HF_Patch#1]
![IMG_1058](https://github.com/ManlyMarco/HC-HF_Patch/assets/145298412/5ada56c6-59b2-4013-b12f-b6cca7a7a8e5)

写真のようなアラートが出て、ゲームが立ち上がりません。対処法を教えてください。

よろしくお願いします

**Comment by ManlyMarco** [comment]
Try moving the game to a simpler directory with no Japanese characters like D:\Games\HC.
If that doesn't help, what game version do you have exactly?

**Comment by vdn39c** [comment]
サポートありがとうございます
マカフィーが一部のファイルを危険と判断し保留していました。解除したところ、無事に開きました

**Comment by ManlyMarco** [comment]
Glad to hear you got it to work! McAfee likes to break mods, yes. It's best to either whitelist or use a different AV.
