### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Ghost9123** [ManlyMarco/HC-HF_Patch#2]
I installed the current HF patch for HoneyCome Come Come Party, and it won't even start. I see the custom launcher, I click start game, see a plugin loader get to 25% and just crashes every time.

**Comment by Ghost9123** [comment]
I found the UnityEngine.CoreModule it said was missing in HoneyCome_come_come_party\BepInEx\HoneyCome\unity-libs and copy/pasted it into HoneyCome_come_come_party\BepInEx\core. It fixed the problem of it saying it was missing. I'm guessing the file was put in the wrong directory or something.

**Comment by ManlyMarco** [comment]
Check your AV.
