### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by yyes86004** [ManlyMarco/HC-HF_Patch#3]
![Screenshot 2024-06-19 161254](https://github.com/ManlyMarco/HC-HF_Patch/assets/173283975/dcd134ff-2e7b-45e9-9c94-61fe08d3981a)
Before the game finishes loading this error shows up if slider unlock is enabled and prevents most features from working

**Comment by ManlyMarco** [comment]
Remove slider unlocker dlls from bepinex\plugins. Next patch will come with a working version.
